### ISSUE TITLE
深度图转换为点云坐标的过程中z的计算逻辑

### ISSUE THREAD

**Issue by FeiMa-REC** [yzn9961/RGBD2PointCloud#5]
### 非常感谢您的分享！
为什么在计算点云坐标点的时候，深度值d要除以50？这个缩放因子是如何确定的。
如果深度数据的单位是毫米的话，要以米为单位显示点云是不是要除以1000

<img width="860" alt="截屏2024-06-28 18 56 29" src="https://github.com/yzn9961/RGBD2PointCloud/assets/62004245/489e4250-fa70-4bf0-8711-1320e3854c2b">

**Comment by Rogerlv51** [comment]
@FeiMa-REC 你理解的没有问题，具体除多少根据你实际采集的点云单位来，扫出来点云是毫米为单位那就除以1000转化为米。（其实转不转也都无所谓，根据实际点云处理来）

**Comment by FeiMa-REC** [comment]
明白了，非常感谢你的答疑！
